### ISSUE TITLE
Exception with PUT Method

### ISSUE THREAD

**Issue by Master-Antonio** [LambdaExpression/RequestBodyParam#5]
Hello, with POST Method all work perfectly, but with PUT Method and 2 parameters in body the server generate a Exception.
`com.github.lambdaexpression.exception.HttpMediaTypeOrHttpBodyException: Request method exception :public org.springframework.http.ResponseEntity<PACKAGE.dto.PostDTO> ........controllers.PostController.editExist(int,PACKAGE.dto.PostDTO,PACKAGE.dto.UserDTO), please check the cn.kknotes.open.bean.MultiReadRequestBean filter condition ( Default ContentType or HttpMethod ERROR ) `

```
@RequestMapping(value = "/posts/{id}/edit", method = RequestMethod.PUT)
    public ResponseEntity<PostDTO> editExist(@PathVariable("id") int idPost, @RequestBodyParam(value = "post") PostDTO postDTO, @RequestBodyParam(value = "user") UserDTO currentUser) { }
```

**Comment by LambdaExpression** [comment]
Have you already set [MultiReadRequestBean](https://github.com/LambdaExpression/RequestBodyParam#2multireadrequestbean) ?
If has multiReadRequestBean, can provide a code demo ?

**Comment by LambdaExpression** [comment]
RequestBodyParam default only supports POST, I would have liked to be determined by the user, the interception of RequestBodyParam. However, considering how many people have recently add PUT, it will be added to the default interception.

**Comment by LambdaExpression** [comment]
Newly updated 2.0.3.RELEASE has supported PUT by default

**Comment by Master-Antonio** [comment]
Thanks so much
